// <auto-generated />
using System;
using Ivirson.LojaHQ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ivirson.LojaHQ.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ivirson.LojaHQ.Models.Revista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Revistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            Autor = "Maurício de Souza",
                            DataCadastro = new DateTime(2020, 11, 9, 11, 14, 8, 581, DateTimeKind.Local).AddTicks(5510),
                            DataLancamento = new DateTime(1990, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagemUrl = "https://organicsnewsbrasil.com.br/wp-content/uploads/2016/01/Revista-Salvando-Vidas_Capa.jpg",
                            Titulo = "Turma da Mônica - Revista 1"
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            Autor = "Akira Toryama",
                            DataCadastro = new DateTime(2020, 11, 9, 11, 14, 8, 586, DateTimeKind.Local).AddTicks(9647),
                            DataLancamento = new DateTime(1989, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagemUrl = "http://www.guiadosquadrinhos.com/edicao/ShowImage.aspx?id=22314&path=conrad/d/dr03310001.jpg&w=400&h=604",
                            Titulo = "Dragon Ball Z - Revista 1"
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            Autor = "Marvel Comics",
                            DataCadastro = new DateTime(2020, 11, 9, 11, 14, 8, 586, DateTimeKind.Local).AddTicks(9966),
                            DataLancamento = new DateTime(2000, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImagemUrl = "https://cdn.awsli.com.br/393/393351/produto/40009441/15cfeba375.jpg",
                            Titulo = "Vingadores - Revista 1"
                        });
                });

            modelBuilder.Entity("Ivirson.LojaHQ.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Login = "admin",
                            Nome = "Usuario Admin",
                            Role = "Admin",
                            Senha = "senhateste"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Login = "usuario",
                            Nome = "Usuario",
                            Role = "Usuario",
                            Senha = "senhateste"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
